---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.36.0"
    hooks:
      - id: yamllint
