---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
configMapGenerator:
  - name: init-sh
    options:
      disableNameSuffixHash: true
    files:
      - init.sh
