---
kind: Namespace
apiVersion: v1
metadata:
  name: &name metrics-server
  labels:
    app.kubernetes.io/name: *name
  annotations:
    argocd.argoproj.io/sync-options: >-
      Delete=false,
      Force=false,
      Prune=false,
      Replace=false,
      ServerSideApply=true
