---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
spec:
  description: "Project for Guestbook"
  destinations:
    - namespace: "guestbook"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "guestbook"
