---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: "Project for Infra Applications"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
