---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
resources:
  - cm_initial-script
  - _ns.yaml
  - ing_cosmos.yaml
  - sts_cosmos.yaml
  - svc_cosmos.yaml
