---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: test-argo
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: >-
      Prune=false,
      Replace=false,
      Force=false
