---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/kukaryambik/argocd-cluster.git
        revision: HEAD
        directories:
          - path: cluster/core/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: '{{ default "" .syncOptions }}'
        argocd.argoproj.io/sync-wave: "{{ default 0 .syncWave }}"
      name: "core--{{.path.basenameNormalized}}"
      namespace: argocd
    spec:
      destination:
        namespace: "{{.path.basenameNormalized}}"
        server: "https://kubernetes.default.svc"
      project: default
      source:
        path: "{{.path.path}}"
        repoURL: https://github.com/kukaryambik/argocd-cluster.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
