---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
spec:
  project: default
  source:
    repoURL: https://github.com/kukaryambik/argocd-cluster.git
    targetRevision: HEAD
    path: cluster/init
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
