---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
namespace: argocd
resources:
  - app_init.yaml
  - appproj_default.yaml
  - appset_main.yaml
helmCharts:
  - name: argo-cd
    repo: "https://argoproj.github.io/argo-helm"
    version: v5.21.0
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesInline:
      createAggregateRoles: true
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
        params:
          application.namespaces: "*"
      controller:
        clusterAdminAccess:
          enabled: true
