---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
configMapGenerator:
  - name: initial-script
    options:
      disableNameSuffixHash: true
    files:
      - initial-script.sh
