---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Meta Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: 'Namespace'
  namespaceResourceWhitelist:
  - group: 'argoproj.io'
    kind: 'Application'
  - group: 'argoproj.io'
    kind: 'AppProject'
